### PR TITLE
Bringing Forks Together

### PR DESCRIPTION
**Pull request by bislewl**

### CODE REVIEW

**Comment by DonThorntonJr** [comment]
I like most of these changes/updates but be aware that I forked the base to make significant changes and customizations to suit my needs and this fork was never meant to be merged bak into the base as a whole.

I will attempt a "Squash and merge" to a single commit to ensure that the changes and updates do not conflict with my changes and if so I might revert back to my current base.

**Comment by DonThorntonJr** [comment]
just finished cleaning up and "fixing" (*) "Squash and merge" process but not fully tested so...

(*) - the code is very sloppy and I'm trying to clean it up as much as possible but there is a lot of redundant code that needs to be consolidated.

**Comment by DonThorntonJr** [comment]
the only update that was not working was the "best bet tie breaker" code so I commented it out

**Comment by DonThorntonJr** [comment]
I will be testing both the pre and post merge code through the end of week 1 but so far it looks good.

pre-merge

post-merge

**Comment by bislewl** [comment]
@DonThorntonJr  Please let me know your results!

I'm not sure of my future of my involvement of this project as I was unable to make a viable group/league this year. if interested in the domain pick2winfootball.com please let me know!

**Pull request merged**
